sudo: required
language: generic
services:
- docker
before_install:
- docker-compose up -d
script:
- echo $DJANGO_SECRET_KEY
- echo "DONE"
#- docker-compose exec django python manage.py test
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "Esusu-v1"
  env: "EsusuV1-env"
  bucket_name: "elasticbeanstalk-us-east-2-745020165956"
  bucket_path: "EsusuV1-env"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
